import * as searchByName from './js/Alex/searchByName';
import * as authorization from './js/Alex/authorization';
import * as renderLettersFilter from './js/Ira/renderLettersFilter';
import * as mobileMenu from './js/Ira/mobileMenu';
import * as favoriteCocktails from './js/Vitalik/favoriteCocktails';
import * as favoriteIngridients from './js/Vitalik/favoriteIngridients';
import * as themeChanger from './js/Vitalik/themeChanger';
import * as pagination from './js/Volodymyr/pagination';
import * as searchByLetter from './js/Volodymyr/searchByLetter';
